### ISSUE TITLE
Allow newer options from `Intl.NumberFormat` like `trailingZeroDisplay`

### ISSUE THREAD

**Issue by piotrkulpinski** [barvian/number-flow#64]
### NumberFlow version

@number-flow/react@0.2.3

### Framework version

react@18.3.0

### Describe the bug and the steps to reproduce it

Hi, 
Would it be possible to allow setting newer options from `Intl.NumberFormat` like [trailingZeroDisplay](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#trailingzerodisplay)?
I assume it's just a matter of updating the TypeScript target option, as the option works correctly.

![CleanShot 2024-11-15 at 11 18 57](https://github.com/user-attachments/assets/2ecc8b38-328f-4685-96c1-11b19daf8ffd)

**Comment by barvian** [comment]
Hi 👋, thanks for filing. I think this is determined by your project's tsconfig because the `Intl.NumberFormatOptions` types aren't bundled in. I can see the type in the `site/` project which uses the same package:

<img width="598" alt="image" src="https://github.com/user-attachments/assets/a3d9251e-ca1f-424a-a1bd-4e0aca7e8e33">

**Comment by piotrkulpinski** [comment]
You're right. I had to update the `target` option in tsconfig to `ESNext` 👍
