### ISSUE TITLE
Number flies off the page when using antd Tabs component

### ISSUE THREAD

**Issue by ytkimirti** [barvian/number-flow#9]
The component looks really good, I wanted to use it in my project and stumbled upon this bug.

It's quite specific. It happened when using antd's `Tabs` component.

- It does not happen when `destroyInactiveTabPane: true` in antd
- It does not happen when there is no update (you can remove the `useState` to test)

I don't have much experience with framer motion so I couldn't go deeper, maybe the problem is from antd or framer motion but I am not sure.

Minimal reproduction: https://codesandbox.io/p/devbox/6vsgx6

**Comment by barvian** [comment]
Hey, thanks for filing and the kind words 👋. I think this happens because antd hides the tabs by default instead of removing them from the DOM. I added the `destroyInactiveTabPane` prop and it seemed to mitigate the issue: [sandbox](https://codesandbox.io/p/devbox/6vsgx6?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0mm7fs400073b6jnv3r1qu3%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0mm7fs400023b6jd2mi8oa0%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0mm7fs400053b6jymxn8pu3%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0mm7fs400063b6j0f0o5s2h%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0mm7fs400023b6jd2mi8oa0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0mm7fs400013b6jr6xf88d3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm0mm7fs400023b6jd2mi8oa0%2522%252C%2522activeTabId%2522%253A%2522cm0mm7fs400013b6jr6xf88d3%2522%257D%252C%2522cm0mm7fs400063b6j0f0o5s2h%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm0mm7fs400063b6j0f0o5s2h%2522%257D%252C%2522cm0mm7fs400053b6jymxn8pu3%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0mm7fs400033b6jh2b9b07f%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522cm0mm7fs400043b6jpq0ictvl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cm0mhud3d00icdjge1toz17qb%2522%257D%255D%252C%2522id%2522%253A%2522cm0mm7fs400053b6jymxn8pu3%2522%252C%2522activeTabId%2522%253A%2522cm0mm7fs400033b6jh2b9b07f%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D). Curious to hear your thoughts.

**Comment by ytkimirti** [comment]
Yeah, could there be a fix? Maybe an option in framer motion?

**Comment by barvian** [comment]
Not that I'm aware of but I'd be interested if you found one! Would the `destroyInactiveTabPane` prop be viable for you?

**Comment by ytkimirti** [comment]
Unfortunately no, if I find time, I will look further into it
